:: PAGE ACCESS TOKEN 
set AMP_ACCESS_TOKEN=EAAKHlnGZCLx4BADvtSU5ZC7C98vb8Vq0DfRTBUV8zDKCNZCil3A744ZCa5PAYYsYsflkxuo35pQanvchP9gcMOgJJ6EAvZAsoQ2fm7K2s3rYTgHyrGNZAr1mB90qZA065p4In34vEPZA4K1ZBObMfolyIc0N9OmwoD6za48moOdlSu66jrrtZCmtXR

:: PAGE VERIF TOKEN
set AMP_VERIF_TOKEN=KALOAPP

:: DATABASE AUTHENTIFICATION
set ADAPTER=SQLITE
:: ADAPTER=MYSQL

::::: CASE MYSQL ADAPTER
set DB_HOST=
set DB_USER=
set DB_PASSWORD=
set DB_NAME=
set DB_PORT=3306

:: CASE SQLITE ADAPTER
set DB_FILE=ampalibe.db


:: APPLICATION CONFIGURATION
set AMP_HOST=0.0.0.0
set AMP_PORT=4555

:: URL APPLICATION
set AMP_URL=

