:: PAGE ACCESS TOKEN 
set AMP_ACCESS_TOKEN=EAAKHlnGZCLx4BAOPpB40mMLfH1ngdMZCfeEZBj7vQSvJVH42AvJ5ZAJ5AwOfRXqLImXJk73qy62KJUUQ4JZBbzgcZBBmZCJgsZAnSvyDQtmB7gZAx4cPfZBnqbGfxQF8cZB680h2WPD30kx8snevjwLGwemrZA3Pu8sKy3pLqxJsuNJXqOAmRDVJxycc

:: PAGE VERIF TOKEN
set AMP_VERIF_TOKEN=KALOAPP

:: DATABASE AUTHENTIFICATION
set ADAPTER=SQLITE
:: ADAPTER=MYSQL

::::: CASE MYSQL ADAPTER
set DB_HOST=
set DB_USER=
set DB_PASSWORD=
set DB_NAME=
set DB_PORT=3306

:: CASE SQLITE ADAPTER
set DB_FILE=ampalibe.db


:: APPLICATION CONFIGURATION
set AMP_HOST=0.0.0.0
set AMP_PORT=4555

:: URL APPLICATION
set AMP_URL=

